#45 Created the api requests functions for the user, moved the files …
mz106/climbing-buddy-fe pull request #46
Opened 2022-07-20 01:50 UTC by bar-alex

…out of signupOrLogin folder as they do more than signup and login and to reduce complexity

2022-07-20 10:19 UTC, mz106 requested changes
I shall review the folder structure. It should be arranged so that each file is named to reflect functionality rather than general functions i.e. fetchRequestsSignupLogin.js

2022-07-20 10:19 UTC, mz106 commented on src/functions/fetchRequests/fetchRequestsUser.js
> +        const res = await fetch(`${process.env.REACT_APP_REST_API}/user`, {
This endpoint does not exist please amend to /user/register.

In addition, please rename the function to registerUser

2022-07-20 10:19 UTC, mz106 commented on src/functions/fetchRequests/fetchRequestsUser.js
> +        // since Michael doesn't want the token in localStorage, attach it to userObj
This is fine for now. I'm going to look into cookies for the token storage. If you have a look into them them please let me know.

2022-07-20 10:19 UTC, mz106 commented on src/functions/fetchRequests/fetchRequestsUser.js
> +// updateUser( {userObj}, setUser, token ) => fetch(); use setUser( user );
We don't yet know how the user will be updated, if at all. Please remove for now.

2022-07-20 10:19 UTC, mz106 commented on src/functions/fetchRequests/fetchRequestsUser.js
> +export const deleteUser = async (userObj, setUser) => {
We don't yet know how the user will be deleted, if at all. Please remove for now.

2022-07-20 10:19 UTC, mz106 commented on src/functions/fetchRequests/fetchRequestsUser.js
> +        const data = await res.json();
Please remove console log before pushing

2022-07-20 10:19 UTC, mz106 commented on src/functions/fetchRequests/fetchRequestsUser.js
> +// retrieveUserByUsername( username ) => fetch(token); retrieve userObj
We don't know how users will be retrieved or in what context. Please reomve to avoid confusion

2022-07-20 10:19 UTC, mz106 commented on src/functions/fetchRequests/fetchRequestsUser.js
> +// retrieveUserFriends( setFriends ) => fetch(token); retrieve [userObj,]
We don't know how the user will interact with friends. Please remove to avoid confusion

2022-07-20 10:19 UTC, mz106 commented on src/functions/fetchRequests/fetchRequestsUser.js
> +// :: users - holds the users
please edit the to notes to reflect the user data on the BE.

2022-07-21 22:47 UTC, bar-alex commented
Changed back the file structure and made all changes that Michael requested.

2022-07-22 10:38 UTC, mz106 approved these changes
Approved

2022-07-23 16:19 UTC, merged